import type { Metadata } from "next";
import { Anton_SC, Roboto } from 'next/font/google'

import Header from '@/src/app/components/header/header';
import Footer from '@/src/app/components/footer/footer';

import "./globals.css";

import '@/src/app/styles/global/reset.css'
import '@/src/app/styles/global/global.scss'
import css from '@/src/app/styles/Layout.module.scss';

import 'swiper/swiper-bundle.css';

const anton_sc = Anton_SC({
  weight: "400",
  variable: '--font-anton_sc',
  subsets: ["latin"],
})
 
const roboto = Roboto({
  weight: ['400', '700'],
  variable: '--font-roboto',
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Just English Please!</title>
        <meta name="description" content="" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={`${anton_sc.variable} ${roboto.variable} antialiased ${css.body}`}
      >
        <div className={css.inner}>
          <Header />
            {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
