import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from '@/src/app/components/header/header';
import Footer from '@/src/app/components/footer/footer';

import "./globals.css";

import '@/src/app/styles/global/reset.css'
import '@/src/app/styles/global/global.scss'
import css from '@/src/app/styles/Layout.module.scss';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Just English Please!</title>
        <meta name="description" content="" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${css.body}`}
      >
        <div className={css.inner}>
          <Header />
            {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
